
# J2735_MessageSet is the python code generated by pycrate from ASN.1 files
from j2735 import MapData
import json

#
# MessageFrame (MF)
#
class j2735_map(MapData):
  def __init__(self):
    self.json = ""
    self.msg = {}
    super().__init__()
