
# J2735_MessageSet is the python code generated by pycrate from ASN.1 files
from j2735 import SPAT
import json

#
# MessageFrame (MF)
#
class j2735_spat(SPAT):
  def __init__(self):
    self.json = ""
    self.msg = {}
    super().__init__()
