# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QProgressBar,
    QPushButton, QSizePolicy, QStatusBar, QToolBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(661, 411)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lblTitle = QLabel(self.centralwidget)
        self.lblTitle.setObjectName(u"lblTitle")
        self.lblTitle.setGeometry(QRect(95, 6, 471, 18))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lblTitle.setFont(font)
        self.lblInput = QLabel(self.centralwidget)
        self.lblInput.setObjectName(u"lblInput")
        self.lblInput.setGeometry(QRect(6, 44, 81, 16))
        font1 = QFont()
        font1.setBold(True)
        self.lblInput.setFont(font1)
        self.inputFile = QLineEdit(self.centralwidget)
        self.inputFile.setObjectName(u"inputFile")
        self.inputFile.setGeometry(QRect(95, 45, 471, 30))
        self.inputFile.setClearButtonEnabled(True)
        self.btnFile = QPushButton(self.centralwidget)
        self.btnFile.setObjectName(u"btnFile")
        self.btnFile.setGeometry(QRect(571, 44, 84, 32))
        self.lblOutput = QLabel(self.centralwidget)
        self.lblOutput.setObjectName(u"lblOutput")
        self.lblOutput.setGeometry(QRect(6, 82, 81, 16))
        self.lblOutput.setFont(font1)
        self.outputDir = QLineEdit(self.centralwidget)
        self.outputDir.setObjectName(u"outputDir")
        self.outputDir.setGeometry(QRect(95, 83, 471, 30))
        self.outputDir.setReadOnly(False)
        self.outputDir.setClearButtonEnabled(True)
        self.btnDir = QPushButton(self.centralwidget)
        self.btnDir.setObjectName(u"btnDir")
        self.btnDir.setGeometry(QRect(571, 82, 84, 32))
        self.lblRX = QLabel(self.centralwidget)
        self.lblRX.setObjectName(u"lblRX")
        self.lblRX.setGeometry(QRect(394, 180, 41, 18))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setUnderline(True)
        self.lblRX.setFont(font2)
        self.lblRX.setAlignment(Qt.AlignCenter)
        self.convertFile = QPushButton(self.centralwidget)
        self.convertFile.setObjectName(u"convertFile")
        self.convertFile.setGeometry(QRect(100, 120, 121, 34))
        self.convertFile.setFont(font)
        self.lblBSM = QLabel(self.centralwidget)
        self.lblBSM.setObjectName(u"lblBSM")
        self.lblBSM.setGeometry(QRect(294, 206, 91, 16))
        self.lblBSM.setFont(font1)
        self.lblMAP = QLabel(self.centralwidget)
        self.lblMAP.setObjectName(u"lblMAP")
        self.lblMAP.setGeometry(QRect(294, 230, 91, 16))
        self.lblMAP.setFont(font1)
        self.lblSPAT = QLabel(self.centralwidget)
        self.lblSPAT.setObjectName(u"lblSPAT")
        self.lblSPAT.setGeometry(QRect(294, 250, 91, 16))
        self.lblSPAT.setFont(font1)
        self.lblRTCM = QLabel(self.centralwidget)
        self.lblRTCM.setObjectName(u"lblRTCM")
        self.lblRTCM.setGeometry(QRect(294, 270, 91, 16))
        self.lblRTCM.setFont(font1)
        self.lblOther = QLabel(self.centralwidget)
        self.lblOther.setObjectName(u"lblOther")
        self.lblOther.setGeometry(QRect(294, 290, 91, 16))
        self.lblOther.setFont(font1)
        self.lblError = QLabel(self.centralwidget)
        self.lblError.setObjectName(u"lblError")
        self.lblError.setGeometry(QRect(294, 310, 91, 16))
        self.lblError.setFont(font1)
        self.lblTotal = QLabel(self.centralwidget)
        self.lblTotal.setObjectName(u"lblTotal")
        self.lblTotal.setGeometry(QRect(294, 330, 91, 16))
        self.lblTotal.setFont(font1)
        self.exitButton = QPushButton(self.centralwidget)
        self.exitButton.setObjectName(u"exitButton")
        self.exitButton.setGeometry(QRect(570, 270, 84, 32))
        self.chkDebugLog = QCheckBox(self.centralwidget)
        self.chkDebugLog.setObjectName(u"chkDebugLog")
        self.chkDebugLog.setGeometry(QRect(30, 160, 211, 20))
        self.chkBinMaps = QCheckBox(self.centralwidget)
        self.chkBinMaps.setObjectName(u"chkBinMaps")
        self.chkBinMaps.setGeometry(QRect(30, 190, 241, 20))
        self.msgBSMrx = QLabel(self.centralwidget)
        self.msgBSMrx.setObjectName(u"msgBSMrx")
        self.msgBSMrx.setGeometry(QRect(394, 206, 81, 18))
        self.msgBSMrx.setFrameShape(QFrame.Panel)
        self.msgBSMrx.setFrameShadow(QFrame.Sunken)
        self.msgBSMrx.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.msgMAPrx = QLabel(self.centralwidget)
        self.msgMAPrx.setObjectName(u"msgMAPrx")
        self.msgMAPrx.setGeometry(QRect(394, 230, 81, 18))
        self.msgMAPrx.setFrameShape(QFrame.Panel)
        self.msgMAPrx.setFrameShadow(QFrame.Sunken)
        self.msgMAPrx.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.msgSPATrx = QLabel(self.centralwidget)
        self.msgSPATrx.setObjectName(u"msgSPATrx")
        self.msgSPATrx.setGeometry(QRect(394, 250, 81, 18))
        self.msgSPATrx.setFrameShape(QFrame.Panel)
        self.msgSPATrx.setFrameShadow(QFrame.Sunken)
        self.msgSPATrx.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.msgRTCMrx = QLabel(self.centralwidget)
        self.msgRTCMrx.setObjectName(u"msgRTCMrx")
        self.msgRTCMrx.setGeometry(QRect(394, 270, 81, 18))
        self.msgRTCMrx.setFrameShape(QFrame.Panel)
        self.msgRTCMrx.setFrameShadow(QFrame.Sunken)
        self.msgRTCMrx.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.msgOtherRx = QLabel(self.centralwidget)
        self.msgOtherRx.setObjectName(u"msgOtherRx")
        self.msgOtherRx.setGeometry(QRect(394, 290, 81, 18))
        self.msgOtherRx.setFrameShape(QFrame.Panel)
        self.msgOtherRx.setFrameShadow(QFrame.Sunken)
        self.msgOtherRx.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.msgErrorCnt = QLabel(self.centralwidget)
        self.msgErrorCnt.setObjectName(u"msgErrorCnt")
        self.msgErrorCnt.setGeometry(QRect(394, 310, 81, 18))
        self.msgErrorCnt.setFrameShape(QFrame.Panel)
        self.msgErrorCnt.setFrameShadow(QFrame.Sunken)
        self.msgErrorCnt.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.msgTotalRx = QLabel(self.centralwidget)
        self.msgTotalRx.setObjectName(u"msgTotalRx")
        self.msgTotalRx.setGeometry(QRect(394, 330, 81, 18))
        self.msgTotalRx.setFrameShape(QFrame.Panel)
        self.msgTotalRx.setFrameShadow(QFrame.Sunken)
        self.msgTotalRx.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.msgTotalTx = QLabel(self.centralwidget)
        self.msgTotalTx.setObjectName(u"msgTotalTx")
        self.msgTotalTx.setGeometry(QRect(482, 330, 81, 18))
        self.msgTotalTx.setFrameShape(QFrame.Panel)
        self.msgTotalTx.setFrameShadow(QFrame.Sunken)
        self.msgTotalTx.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lblTX = QLabel(self.centralwidget)
        self.lblTX.setObjectName(u"lblTX")
        self.lblTX.setGeometry(QRect(482, 180, 41, 18))
        self.lblTX.setFont(font2)
        self.lblTX.setFrameShadow(QFrame.Plain)
        self.lblTX.setAlignment(Qt.AlignCenter)
        self.msgBSMtx = QLabel(self.centralwidget)
        self.msgBSMtx.setObjectName(u"msgBSMtx")
        self.msgBSMtx.setGeometry(QRect(482, 206, 81, 18))
        self.msgBSMtx.setFrameShape(QFrame.Panel)
        self.msgBSMtx.setFrameShadow(QFrame.Sunken)
        self.msgBSMtx.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.outputFile = QLabel(self.centralwidget)
        self.outputFile.setObjectName(u"outputFile")
        self.outputFile.setGeometry(QRect(230, 160, 331, 21))
        self.outputFile.setFrameShape(QFrame.Panel)
        self.outputFile.setFrameShadow(QFrame.Sunken)
        self.chkConvertData = QCheckBox(self.centralwidget)
        self.chkConvertData.setObjectName(u"chkConvertData")
        self.chkConvertData.setGeometry(QRect(50, 280, 211, 20))
        self.chkSplitMaps = QCheckBox(self.centralwidget)
        self.chkSplitMaps.setObjectName(u"chkSplitMaps")
        self.chkSplitMaps.setGeometry(QRect(30, 210, 251, 20))
        self.chkSplitMaps.setChecked(True)
        self.chkSeparateMaps = QCheckBox(self.centralwidget)
        self.chkSeparateMaps.setObjectName(u"chkSeparateMaps")
        self.chkSeparateMaps.setGeometry(QRect(50, 230, 241, 20))
        self.chkSeparateMaps.setChecked(False)
        self.chkSplitBsms = QCheckBox(self.centralwidget)
        self.chkSplitBsms.setObjectName(u"chkSplitBsms")
        self.chkSplitBsms.setGeometry(QRect(30, 260, 251, 20))
        self.chkSplitBsms.setChecked(False)
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(227, 130, 341, 23))
        self.progressBar.setValue(0)
        self.progressBar.setOrientation(Qt.Horizontal)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 661, 28))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"NTCNA V2X: J2735 Decoder", None))
        self.lblTitle.setText(QCoreApplication.translate("MainWindow", u"NTCNA J2735 PCAP Decoder to JSON Conversion ", None))
        self.lblInput.setText(QCoreApplication.translate("MainWindow", u"Input File(s):", None))
        self.btnFile.setText(QCoreApplication.translate("MainWindow", u"File", None))
        self.lblOutput.setText(QCoreApplication.translate("MainWindow", u"Output Dir:", None))
        self.btnDir.setText(QCoreApplication.translate("MainWindow", u"Dir", None))
        self.lblRX.setText(QCoreApplication.translate("MainWindow", u"RX", None))
        self.convertFile.setText(QCoreApplication.translate("MainWindow", u"Convert File(s)", None))
        self.lblBSM.setText(QCoreApplication.translate("MainWindow", u"BSM Counts", None))
        self.lblMAP.setText(QCoreApplication.translate("MainWindow", u"MAP Count", None))
        self.lblSPAT.setText(QCoreApplication.translate("MainWindow", u"SPAT Count", None))
        self.lblRTCM.setText(QCoreApplication.translate("MainWindow", u"RTCM Count", None))
        self.lblOther.setText(QCoreApplication.translate("MainWindow", u"Other count", None))
        self.lblError.setText(QCoreApplication.translate("MainWindow", u"Error count", None))
        self.lblTotal.setText(QCoreApplication.translate("MainWindow", u"Total Counts", None))
        self.exitButton.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.chkDebugLog.setText(QCoreApplication.translate("MainWindow", u"Debug Log", None))
        self.chkBinMaps.setText(QCoreApplication.translate("MainWindow", u"Output Binary MAPs", None))
        self.msgBSMrx.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.msgMAPrx.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.msgSPATrx.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.msgRTCMrx.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.msgOtherRx.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.msgErrorCnt.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.msgTotalRx.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.msgTotalTx.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lblTX.setText(QCoreApplication.translate("MainWindow", u"TX", None))
        self.msgBSMtx.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.outputFile.setText("")
        self.chkConvertData.setText(QCoreApplication.translate("MainWindow", u"BSM Conversion of split files", None))
        self.chkSplitMaps.setText(QCoreApplication.translate("MainWindow", u"Output MAPs/SPATs into file by Id", None))
        self.chkSeparateMaps.setText(QCoreApplication.translate("MainWindow", u"Separate MAPs from SPATs", None))
        self.chkSplitBsms.setText(QCoreApplication.translate("MainWindow", u"Split BSMs into files by Id", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

