# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGraphicsView,
    QHeaderView, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTextEdit, QToolBar,
    QTreeView, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1040, 840)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lblTitle = QLabel(self.centralwidget)
        self.lblTitle.setObjectName(u"lblTitle")
        self.lblTitle.setGeometry(QRect(95, 6, 471, 18))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lblTitle.setFont(font)
        self.lblInput = QLabel(self.centralwidget)
        self.lblInput.setObjectName(u"lblInput")
        self.lblInput.setGeometry(QRect(10, 40, 81, 16))
        font1 = QFont()
        font1.setBold(True)
        self.lblInput.setFont(font1)
        self.inputFile = QLineEdit(self.centralwidget)
        self.inputFile.setObjectName(u"inputFile")
        self.inputFile.setGeometry(QRect(90, 30, 761, 30))
        self.inputFile.setClearButtonEnabled(True)
        self.btnFile = QPushButton(self.centralwidget)
        self.btnFile.setObjectName(u"btnFile")
        self.btnFile.setGeometry(QRect(860, 30, 84, 32))
        self.exitButton = QPushButton(self.centralwidget)
        self.exitButton.setObjectName(u"exitButton")
        self.exitButton.setGeometry(QRect(960, 70, 51, 32))
        self.treeView = QTreeView(self.centralwidget)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setGeometry(QRect(320, 180, 711, 591))
        self.chkBSM = QCheckBox(self.centralwidget)
        self.chkBSM.setObjectName(u"chkBSM")
        self.chkBSM.setGeometry(QRect(10, 140, 61, 20))
        self.chkBSM.setChecked(True)
        self.lblInput_2 = QLabel(self.centralwidget)
        self.lblInput_2.setObjectName(u"lblInput_2")
        self.lblInput_2.setGeometry(QRect(10, 110, 131, 16))
        self.lblInput_2.setFont(font1)
        self.chkMAP = QCheckBox(self.centralwidget)
        self.chkMAP.setObjectName(u"chkMAP")
        self.chkMAP.setGeometry(QRect(250, 120, 71, 20))
        self.chkMAP.setChecked(True)
        self.chkSPAT = QCheckBox(self.centralwidget)
        self.chkSPAT.setObjectName(u"chkSPAT")
        self.chkSPAT.setGeometry(QRect(250, 150, 71, 20))
        self.chkSPAT.setChecked(True)
        self.chkRTCM = QCheckBox(self.centralwidget)
        self.chkRTCM.setObjectName(u"chkRTCM")
        self.chkRTCM.setEnabled(True)
        self.chkRTCM.setGeometry(QRect(450, 150, 101, 20))
        self.chkRTCM.setChecked(False)
        self.lblInput_3 = QLabel(self.centralwidget)
        self.lblInput_3.setObjectName(u"lblInput_3")
        self.lblInput_3.setGeometry(QRect(10, 80, 131, 16))
        self.lblInput_3.setFont(font1)
        self.timeStart = QLineEdit(self.centralwidget)
        self.timeStart.setObjectName(u"timeStart")
        self.timeStart.setGeometry(QRect(160, 70, 141, 30))
        self.timeStart.setClearButtonEnabled(True)
        self.timeEnd = QLineEdit(self.centralwidget)
        self.timeEnd.setObjectName(u"timeEnd")
        self.timeEnd.setGeometry(QRect(380, 70, 141, 30))
        self.timeEnd.setClearButtonEnabled(True)
        self.comboBsmID = QComboBox(self.centralwidget)
        self.comboBsmID.setObjectName(u"comboBsmID")
        self.comboBsmID.setGeometry(QRect(120, 140, 91, 30))
        self.lblInput_4 = QLabel(self.centralwidget)
        self.lblInput_4.setObjectName(u"lblInput_4")
        self.lblInput_4.setGeometry(QRect(140, 120, 61, 16))
        font2 = QFont()
        font2.setBold(False)
        self.lblInput_4.setFont(font2)
        self.comboMapID = QComboBox(self.centralwidget)
        self.comboMapID.setObjectName(u"comboMapID")
        self.comboMapID.setGeometry(QRect(320, 140, 111, 30))
        self.lblInput_5 = QLabel(self.centralwidget)
        self.lblInput_5.setObjectName(u"lblInput_5")
        self.lblInput_5.setGeometry(QRect(330, 120, 81, 16))
        self.lblInput_5.setFont(font2)
        self.listWidget = QListWidget(self.centralwidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(5, 180, 311, 591))
        font3 = QFont()
        font3.setFamilies([u"Monospace"])
        self.listWidget.setFont(font3)
        self.comboViewMode = QComboBox(self.centralwidget)
        self.comboViewMode.setObjectName(u"comboViewMode")
        self.comboViewMode.setGeometry(QRect(920, 140, 91, 30))
        self.lblInput_6 = QLabel(self.centralwidget)
        self.lblInput_6.setObjectName(u"lblInput_6")
        self.lblInput_6.setGeometry(QRect(840, 150, 81, 16))
        self.lblInput_6.setFont(font1)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(320, 181, 711, 591))
        self.graphicsView.setFont(font3)
        self.setStart = QPushButton(self.centralwidget)
        self.setStart.setObjectName(u"setStart")
        self.setStart.setGeometry(QRect(90, 70, 61, 32))
        self.setEnd = QPushButton(self.centralwidget)
        self.setEnd.setObjectName(u"setEnd")
        self.setEnd.setGeometry(QRect(310, 70, 61, 32))
        self.clearTimes = QPushButton(self.centralwidget)
        self.clearTimes.setObjectName(u"clearTimes")
        self.clearTimes.setGeometry(QRect(530, 70, 61, 32))
        self.chkTX = QCheckBox(self.centralwidget)
        self.chkTX.setObjectName(u"chkTX")
        self.chkTX.setGeometry(QRect(70, 130, 51, 20))
        self.chkTX.setChecked(True)
        self.chkRX = QCheckBox(self.centralwidget)
        self.chkRX.setObjectName(u"chkRX")
        self.chkRX.setGeometry(QRect(70, 150, 51, 20))
        self.chkRX.setChecked(True)
        self.chkPDMPVD = QCheckBox(self.centralwidget)
        self.chkPDMPVD.setObjectName(u"chkPDMPVD")
        self.chkPDMPVD.setEnabled(True)
        self.chkPDMPVD.setGeometry(QRect(710, 110, 101, 20))
        self.chkSRMSSM = QCheckBox(self.centralwidget)
        self.chkSRMSSM.setObjectName(u"chkSRMSSM")
        self.chkSRMSSM.setEnabled(True)
        self.chkSRMSSM.setGeometry(QRect(710, 150, 91, 20))
        self.chkSRMSSM.setChecked(False)
        self.chkTIM = QCheckBox(self.centralwidget)
        self.chkTIM.setObjectName(u"chkTIM")
        self.chkTIM.setEnabled(True)
        self.chkTIM.setGeometry(QRect(570, 150, 121, 20))
        self.chkTIM.setChecked(False)
        self.chkPSM = QCheckBox(self.centralwidget)
        self.chkPSM.setObjectName(u"chkPSM")
        self.chkPSM.setEnabled(True)
        self.chkPSM.setGeometry(QRect(570, 130, 91, 20))
        self.chkCCM = QCheckBox(self.centralwidget)
        self.chkCCM.setObjectName(u"chkCCM")
        self.chkCCM.setEnabled(True)
        self.chkCCM.setGeometry(QRect(570, 110, 81, 20))
        self.chkCustom = QCheckBox(self.centralwidget)
        self.chkCustom.setObjectName(u"chkCustom")
        self.chkCustom.setEnabled(True)
        self.chkCustom.setGeometry(QRect(840, 110, 81, 20))
        self.chkCustom.setChecked(False)
        self.textMessage = QTextEdit(self.centralwidget)
        self.textMessage.setObjectName(u"textMessage")
        self.textMessage.setGeometry(QRect(323, 176, 711, 601))
        self.textMessage.setFont(font3)
        self.chkRGA = QCheckBox(self.centralwidget)
        self.chkRGA.setObjectName(u"chkRGA")
        self.chkRGA.setGeometry(QRect(450, 120, 61, 20))
        self.chkRGA.setChecked(False)
        self.chkSDSM = QCheckBox(self.centralwidget)
        self.chkSDSM.setObjectName(u"chkSDSM")
        self.chkSDSM.setEnabled(True)
        self.chkSDSM.setGeometry(QRect(710, 130, 111, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1040, 30))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)

        self.comboViewMode.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"NTCNA V2X: J2735 Viewer", None))
        self.lblTitle.setText(QCoreApplication.translate("MainWindow", u"NTCNA J2735 JSON Viewer", None))
        self.lblInput.setText(QCoreApplication.translate("MainWindow", u"Input File:", None))
        self.btnFile.setText(QCoreApplication.translate("MainWindow", u"File", None))
        self.exitButton.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.chkBSM.setText(QCoreApplication.translate("MainWindow", u"BSM", None))
        self.lblInput_2.setText(QCoreApplication.translate("MainWindow", u"Message Filters:", None))
        self.chkMAP.setText(QCoreApplication.translate("MainWindow", u"MAP", None))
        self.chkSPAT.setText(QCoreApplication.translate("MainWindow", u"SPAT", None))
        self.chkRTCM.setText(QCoreApplication.translate("MainWindow", u"NMEA/RTCM", None))
        self.lblInput_3.setText(QCoreApplication.translate("MainWindow", u"Time Filter:", None))
        self.lblInput_4.setText(QCoreApplication.translate("MainWindow", u"BSM ID:", None))
        self.lblInput_5.setText(QCoreApplication.translate("MainWindow", u"MAP/SPAT ID:", None))
        self.lblInput_6.setText(QCoreApplication.translate("MainWindow", u"View Mode:", None))
        self.setStart.setText(QCoreApplication.translate("MainWindow", u"Set Start", None))
        self.setEnd.setText(QCoreApplication.translate("MainWindow", u"Set End", None))
        self.clearTimes.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.chkTX.setText(QCoreApplication.translate("MainWindow", u"TX", None))
        self.chkRX.setText(QCoreApplication.translate("MainWindow", u"RX", None))
        self.chkPDMPVD.setText(QCoreApplication.translate("MainWindow", u"PDM/PVD", None))
        self.chkSRMSSM.setText(QCoreApplication.translate("MainWindow", u"SRM/SSM", None))
        self.chkTIM.setText(QCoreApplication.translate("MainWindow", u"TIM/RSM/RWM", None))
        self.chkPSM.setText(QCoreApplication.translate("MainWindow", u"PSM/PSM2", None))
        self.chkCCM.setText(QCoreApplication.translate("MainWindow", u"CCM", None))
        self.chkCustom.setText(QCoreApplication.translate("MainWindow", u"Custom", None))
        self.chkRGA.setText(QCoreApplication.translate("MainWindow", u"RGA", None))
        self.chkSDSM.setText(QCoreApplication.translate("MainWindow", u"SDSM/MSCM", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

